version: 0.1
phases:
    pre_build:
        commands:
            - echo "Entered the pre-build phase"
            - npm install
    build:
        commands:
            - echo "Entered the build phase"
            - ./scripts/make-cookies-secure.sh
            - echo "make-cookies-secure ran "
    post_build:
        commands:
            - echo "Entered the post-build phase"
artifacts:
    files:
        - "**/*"
